### ISSUE TITLE
加入SIP检查吧

### ISSUE THREAD

**Issue by PMheart** [syscl/Enable-HiDPI-OSX#1]
RT
免得 1011被坑。。。

FEEL FREE TO CLOSE THIS

**Comment by arslan2012** [comment]
不会被坑的，SIP开启状态下，操作会直接被系统拒绝，不会有问题

**Comment by PMheart** [comment]
可以学toleda啊 侦测到文件系统保护开启时退出 或者生成文件到桌面。。

**Comment by syscl** [comment]
toleda的那个检测是用的Pikeralpha写的C. 确实是一个很贴心的提示, 虽然作为黑果我觉得没必要, 但是今晚有一个白果的朋友问了我如何使用这些脚本, 所以以后想办法加入吧.

**Comment by PMheart** [comment]
好吧。。。以前写个cpp的kext像要命一样= =
白果就得进recovery去 csrutil enable --without fs 了呗

**Comment by syscl** [comment]
用C啊, CPP繁琐. 我看Pike那个脚本只有三十多行好像.

**Comment by PMheart** [comment]
= =cpp废话比较多 不过写kext必须得cpp啊

**Comment by syscl** [comment]
没办法，历史遗留问题，98年的时候，CPP的占有率好像76%, 如今只有40多了。

**Comment by PMheart** [comment]
= =98年我还没出生
