### ISSUE TITLE
May get a wrong result while calculating decimal data to hexdecimal data.

### ISSUE THREAD

**Issue by PMheart** [syscl/Enable-HiDPI-OSX#11]
For instance:
While typing 3840x2160, well, these are decimal datas. But when you convert 3840 to hexdecimal data, it should be 0x1e00. 
But your code...
`gRes_VAL=$(echo "00000$gHeight 00000$gWide 00000001 00200000")`
So, 000001e00 is obviously wrong. So now I understand why your script cannot enable HiDPI. That is, when typing 1920x1080, the 2x resoultion, 3840x2160's data is wrong!!!

**Comment by Artoria2e5** [comment]
> So, obviously wrong

With `00000001` you should be able to infer that it is a 32-bit hex soup. Where does your "so" come from?

Well it's in fact some simple padding... or why not printf.

**Comment by PMheart** [comment]
Yeah and `00000001 00200000` is a static code and not important. :)
