### ISSUE TITLE
not work  10.11.6

### ISSUE THREAD

**Issue by snowjade** [syscl/Enable-HiDPI-OSX#12]
Xiang-mbp:~ Xiang$ ~/enable-HiDPI.sh
 Multi monitors detected, please choose target monitor: 
 [ 1 ] 0610::2aa0
 [ 2 ] 2163::0000

Please choose the desired display for enable Hi-DPI (Exit/1-2) ? 1
Password:
[  OK  ]  Remove /Users/Xiang/DisplayVendorID-0610.
Enter the Resolution you want to enable HiDPI(e.g. 1600x900, 1440x910, ...), enter 0 to quit: 1920x1080
Enter the Resolution you want to enable HiDPI(e.g. 1600x900, 1440x910, ...), enter 0 to quit: 0
[ ---> ]  Backuping origin Display Information...
cp: /System/Library/Displays/Contents/Resources/Overrides/DisplayVendorID-0610: Operation not permitted
cp: /Users/Xiang/DisplayVendorID-0610: unable to copy extended attributes to /System/Library/Displays/Contents/Resources/Overrides/DisplayVendorID-0610: Operation not permitted
cp: /System/Library/Displays/Contents/Resources/Overrides/DisplayVendorID-0610/DisplayProductID-a02a: No such file or directory
[  OK  ]  Done, Please Reboot to see the change! Pay attention to use Retina Display Menu(RDM) to select the HiDPI resolution!.
Xiang-mbp:~ Xiang$

**Comment by syscl** [comment]
@snowjade 
Please disable SIP. The execution shows that cp(copy) cannot be executed correctly.

syscl
