### ISSUE TITLE
10.12GM版本下开启后重启读完进度条直接重启了。。。

### ISSUE THREAD

**Issue by lgs3137** [syscl/Enable-HiDPI-OSX#13]
10.12GM版本下开启后重启读完进度条直接重启了。。。
感觉应该是注入的驱动改了？
没开-v....暂时获取不到日志

**Comment by syscl** [comment]
谢谢你的反馈, 能够提供你的具体设置吗?

包括系统的配置.

syscl

**Comment by lgs3137** [comment]
额，中午我又重新安装了最新的GM第二版，可以正常开启了。。。
挺神奇的。。。
