### ISSUE TITLE
not work in 10.12

### ISSUE THREAD

**Issue by tudows** [syscl/Enable-HiDPI-OSX#14]
the terminate display

Enter the Resolution you want to enable HiDPI(If you want to stop adding or say you just add enough number of HiDPI resolution you want, enter 0: 1920x1080
Enter the Resolution you want to enable HiDPI(If you want to stop adding or say you just add enough number of HiDPI resolution you want, enter 0: 0
[ ---> ]  Backuping origin Display Information...
Password:
2016-09-21 21:55:58.906 defaults[2898:36822] 
Domain (/Library/Preferences/com.apple.windowserver) not found.
Defaults have not been changed.
[  OK  ]  Done, Please Reboot to see the change! Pay attention to use Retina Menu Display to select the HiDPI resolution!.

**Comment by syscl** [comment]
@tudows Please provide the information by the following command line:
```sh
ioreg -lw0 | grep -i "IODisplayEDID"
```

BTW, do you try other value such as 1600x900 as well? 

Wait for your feedback,
syscl

**Comment by tudows** [comment]
the terminate display:

    | |   |   | |   |       "IODisplayEDID" = <00ffffffffffff00410cc6c0b96400000818010380301b782a16c5a456509f26125054bd4b00d1c08180950f9500b30081c001010101023a801871382d40582c4500dc0c1100001e000000ff0055484231343038303235373835000000fc0050484c2032323445350a202020000000fd00384c1e5311000a2020202020200120020323f150010203050607101112131415161f0422230917078301000065030c002000023a801871382d40582c4500dc0c1100001e8c0ad08a20e02d10103e9600dc0c11000018011d007251d01e206e285500dc0c1100001e8c0ad090204031200c405500dc0c1100001800000000000000000000000000000000000000001d>


I don't try the 1600x900 because my monitor is 1920x1080

**Comment by syscl** [comment]
@tudows 
I know there's reason why you use 1920x1080, but if the max resolution of your monitor is 1920x1080, then there's no necessary to add such a resolution. Because, once you added 1920x1080(HiDPI) you will see no difference but push high pressure on graphics card(really bad idea).

But, you can use values which are smaller than 1920x1080, in that case, it will work like a charm.
For example, my Sharp TV has a 1920x1080 res, then I inject 1440x810 for it by Enable-HiDPI, it looks pretty good.

So, don't hesitate to have a try, buddy:)

Wait for your feedback,
syscl

**Comment by tudows** [comment]
But when I use 10.11.4, I use 1920x1080 and Enable-HiDPI-OSX works. And when I screenshot or record the screen, the resolution of picture and the video is 4K. This provide me a high definition material to make video.

**Comment by syscl** [comment]
Wow, weird, can you kindly provide the screenshot for me about all the information, since I have very little time to see this on 10.12, but as you mentioned it succeeded in 10.11, I want to see what's going on to solve your issue.

Thanks,
syscl

**Comment by tudows** [comment]
OK, here is the picture. I run the 
`ioreg -lw0 | grep -i "IODisplayEDID"`
and
`/Users/rabbit/Downloads/HiDPI/enable-HiDPI.sh`

[http://rrabbit.cc/wp-content/uploads/2016/09/Screen-Shot-2016-09-22-at-00.04.51.png](url)

**Comment by syscl** [comment]
@tudows 
the picture cannot be opened.

syscl

**Comment by tudows** [comment]
copy the url and visit it, do not click directly

**Comment by syscl** [comment]
OK, I saw it, I mean in 10.11 and so on, what the RDM displays after injecting res you want?

syscl

**Comment by tudows** [comment]
I open RDM again and want to take a photo to you to show the wrong but very amazing ! HiDPI works normally !! I choose 1920x1080 in the RDM and the resolution of screenshot is 3840 × 2160 normally.

    I remember when I first run the "enable-HiDPI.sh" and then reboot the mac, install the RDM and in the RDM choose 1920x1080, the display area becomes square and the monitor is very indistinct, I take a screenshot and then find that the resolution of screenshot is 3840 x 3360

**Comment by syscl** [comment]
So you mean it works?

Don't hesitate to star this project and share to let more people benefit from it:)

syscl

**Comment by tudows** [comment]
Yeah! It works! Thank you very much.😬

**Comment by syscl** [comment]
@tudows great to hear that!

Star is on the right corner of the project page as well as folk and follow to see update.

syscl

**Comment by syscl** [comment]
@tudows 
And don't forget to close the issue if it did work.

Thanks,
syscl
