### ISSUE TITLE
10.12 success

### ISSUE THREAD

**Issue by imyuyang** [syscl/Enable-HiDPI-OSX#16]
在10.12中成功，按照步骤在RDM中出现自己添加的分辨率选项
$ ~/enable-HiDPI.sh
 Multi monitors detected, please choose target monitor: 
 [ 1 ] 0610::29a0
 [ 2 ] 410c::e908
记住这里外接显示器是选择2，内部显示器是1。若果是内部的话，原文件中是610，不是0610，只需要去/System/Library/Displays/Contents/Resources/Overrides/DisplayVendorID-0610/中把你设置好的文件拖到/System/Library/Displays/Contents/Resources/Overrides/DisplayVendorID-610/中重启就行，记得备份下源文件，还有我发现，10.12中不需要关闭SIP就能成功。感谢作者

**Comment by syscl** [comment]
@imyuyang 感谢反馈, 我会在最近修复 这些日子有点忙.

syscl

**Comment by syscl** [comment]
@imyuyang 你好，请尝试最新版本的enable-HiDPI.sh 以查看是否解决的0610的文件名问题。
