### ISSUE TITLE
Cannot Enable HiDPI in 10.12

### ISSUE THREAD

**Issue by moriwang** [syscl/Enable-HiDPI-OSX#23]
Thanks for your script.
I use a 1080P monitor and DP connection, tried to add 1920x1080, 1600x900, 1400x810, 1280x720.
Then reboot , no new solution in System Preferences or RDM app.
In SwitchResX, it shows the new resolution "Not activated - Invalid?" in custom resolution.
So I guess your script did work, but there must be somewhere wrong to output.

`
    | |   | | |       "IODisplayEDID" = <00ffffffffffff0010aca3a04c36383218190104a5351e783e7e75a755529c270f5054a54b00714f8180a9c0a940d1c0010101010101023a801871382d40582c45000f282100001e000000ff0034435758373536373238364c0a000000fc0044454c4c205532343134480a20000000fd00384c1e5311000a202020202020012c020319f14c9005040302071601141f12132309070783010000023a801871382d40582c45000f282100001e011d8018711c1620582c25000f282100009e011d007251d01e206e2855000f282100001e8c0ad08a20e02d10103e96000f2821000018000000000000000000000000000000000000000000000000000000000000c1>`

**Comment by syscl** [comment]
Hello, you should try to use RDM with this script.

syscl
