### ISSUE TITLE
hd4600，运行脚本修改为1600x900后，重启再用rdm修改为1600x900不生效

### ISSUE THREAD

**Issue by csbssp** [syscl/Enable-HiDPI-OSX#27]
如题，显卡是hd4600

**Comment by syscl** [comment]
@chenshaobo 是不显示还是选了1600x900没有变化？？

syscl

**Comment by chenshaobo** [comment]
选择了1600x900(HiDPI)不生效,但是1280x720（HiDPI)可以生效
感谢你这个开源项目,显示真的清晰了很多@syscl

**Comment by skinnyshy** [comment]
![2017-01-27 11 03 45](https://cloud.githubusercontent.com/assets/12553514/22360750/c6317b8c-e48d-11e6-8845-e7c1c1b512bd.png)
@syscl 请问,gtx770为何1600x900无法启用hidpi

**Comment by syscl** [comment]
@skinnyshy 试一下RDM...

syscl
