### ISSUE TITLE
Vendor 識別問題

### ISSUE THREAD

**Issue by soto2080** [syscl/Enable-HiDPI-OSX#32]
在Vendor只有三個字的時候前面會自動補０而造成plist放到錯誤的vendor而無效

**Comment by syscl** [comment]
你好，请问能否提供相应的EDID信息呢？谢谢！

syscl

**Comment by soto2080** [comment]
`ks-MacBook-Pro:~ k$ ioreg -lw0 | grep IODisplayPrefsKey
    | |   | | |       "IODisplayPrefsKey" = "IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/IGPU@2/AppleIntelFramebuffer@0/display0/AppleBacklightDisplay-9e5-65d"
`
我的情況是這樣9e5變成09e5

**Comment by syscl** [comment]
我会尝试修复这个问题。。谢谢

syscl

**Comment by syscl** [comment]
@soto2080 你好请尝试最新版本的enable-HiDPI.sh以查看是否修复了上述问题。

谢谢，
syscl
