### ISSUE TITLE
6代核显HD530 开启最适分辨率HiDPI无效

### ISSUE THREAD

**Issue by crackself** [syscl/Enable-HiDPI-OSX#35]
机器是Dell7559，6代核显HD530。最大分辨率为1920 x 1080。win10支持的分辨率：
`1920x1080
1680x1050
1600x900
1440x900
1400x1050
1366x768
1360x768
1280x1024
1280x960
1280x800
1280x768
1280x720
1280x600
1152x864
1024x768
800x600`
在Mac OS 10.12.6 用此方法，HiDPI分辨率达不到最大分辨率，屏幕两侧出现黑边。
<img width="321" alt="17cf3506-9bad-4001-b4a2-9a156831d5ce" src="https://user-images.githubusercontent.com/16448332/30374142-79863358-98b6-11e7-99a6-d7ab80a15672.png">

**Comment by coderstory** [comment]
因为id只有三位的情况下自动补0了  需要自己删掉

**Comment by crackself** [comment]
好的，感谢。
