### ISSUE TITLE
报了个语法错误？

### ISSUE THREAD

**Issue by liusunpan** [syscl/Enable-HiDPI-OSX#4]
enable-HiDPI.sh: line 101: 0x4c2d
2163: syntax error in expression (error token is "2163")
101 在这行  gDisplayVendorID=$((0x$gDisplayVendorID_RAW))

**Comment by syscl** [comment]
感谢反馈, 请附上EDID信息, 谢谢;)

**Comment by liusunpan** [comment]
EDID report generated by SwitchResX Version 4.5.3 (Intel - 64-bit) for display iMac


-----------------------------------------------------
------------------- RAW DATA ------------------------
-----------------------------------------------------
      0  1  2  3  4  5  6  7  8  9  A  B  C  D  E  F
-----------------------------------------------------
0  | 00 FF FF FF FF FF FF 00 06 10 12 A0 00 00 00 00
1  | 1C 16 01 04 B5 30 1B 78 22 6F B1 A7 55 4C 9E 25
2  | 0C 50 54 AF CF 00 D1 C0 B3 00 95 00 81 80 81 C0
3  | 81 00 01 01 01 01 56 5E 00 A0 A0 A0 29 50 30 20
4  | 35 00 55 50 21 00 00 1A 00 00 00 FC 00 69 4D 61
5  | 63 0A 20 20 20 20 20 20 20 20 00 00 00 FD 00 38
6  | 4C 1E 53 11 00 0A 20 20 20 20 20 20 00 00 00 FF
7  | 00 30 30 30 30 30 30 30 30 30 30 30 30 31 01 44

-----------------------------------------------------
      0  1  2  3  4  5  6  7  8  9  A  B  C  D  E  F
-----------------------------------------------------
0  | 02 03 1F F1 4C 01 02 03 04 05 07 90 12 13 14 16
1  | 1F 23 09 07 07 83 01 00 00 65 03 0C 00 10 00 02
2  | 3A 80 18 71 38 2D 40 58 2C 45 00 FE 1F 11 00 00
3  | 1E 01 1D 80 18 71 1C 16 20 58 2C 25 00 FE 1F 11
4  | 00 00 9E 01 1D 00 72 51 D0 1E 20 6E 28 55 00 FE
5  | 1F 11 00 00 1E 8C 0A D0 8A 20 E0 2D 10 10 3E 96
6  | 00 FE 1F 11 00 00 18 01 1D 00 BC 52 D0 1E 20 B8
7  | 28 55 40 E8 12 11 00 00 1E 00 00 00 00 00 00 07

**Comment by liusunpan** [comment]
os x 10.11.5

**Comment by liusunpan** [comment]
估计倒时差，在睡觉吧 哈哈

**Comment by syscl** [comment]
能够粘贴下面的数据给我吗？ 我在终端中帮你执行了这段EDID, 没有问题哎.

```sh 
ioreg -lw0 | grep -i "IODisplayEDID"
```

谢谢:)

**Comment by liusunpan** [comment]
| |   |   | |           "IODisplayEDID" = <00ffffffffffff004c2d240137314a4d0d1001036c221b782aaaa5a654549926145054bfef808180714f010101010101010101010101302a009851002a4030701300520e1100001e000000fd00384b1e510e000a202020202020000000fc0053796e634d61737465720a2020000000ff004856474c3333303538340a20200038>
    | |   |   | |           "IODisplayEDID" = <00ffffffffffff0021630000000000000a180104803c2278e23d85a6564a9a24125054afcf00d1c0b3009500818081c0810001010101565e00a0a0a029503020350055502100001a000000fc0048444d490a2020202020202020000000fd00374b0f6319000a202020202020000000ff003030303030303030303030303101aa02031ff14c01020304050790121314161f230907078301000065030c001000023a801871382d40582c4500fe1f1100001e011d8018711c1620582c2500fe1f1100009e011d007251d01e206e285500fe1f1100001e8c0ad08a20e02d10103e9600fe1f11000018011d00bc52d01e20b8285540e8121100001e00000000000007>

**Comment by syscl** [comment]
十分感谢你提供的这么重要的资讯! 看来原因明了了, 你有两个显示器, 所以在
```sh
ioreg -lw0 | grep -i "IODisplayEDID" | sed "/[^<]*</s///" | cut -c 17-20
```
执行之后, 输出的结果是
```sh
4c2d
2163
```
这也是我在设计这个脚本之初没有考虑到的问题, 感谢你提供这么宝贵的信息, 我会添加双/多显示器多支持的! 

谢谢!

**Comment by liusunpan** [comment]
不客气，谢谢

**Comment by syscl** [comment]
感谢你的反馈, 修复了这个错误, 也在Readme中增加了感谢. 

赶紧测试一下吧 ;)

**Comment by liusunpan** [comment]
好的，thanks
