### ISSUE TITLE
提示语修改

### ISSUE THREAD

**Issue by transtone** [syscl/Enable-HiDPI-OSX#5]
非常感谢这个项目，解决了我的大问题，比那些收费的什么工具好用多了。特别是配合RDM。

只是提示语太坑爹了，用错了好几次才反应过来。
`Enter the Resolution you want to enable HiDPI(If you want to stop adding or say you just add enough number of HiDPI resolution you want, enter 0:`

改成：
`Enter the Resolution you want to enable HiDPI(Like 1600x900, ), enter 0 to quit:`
会不会好点？或者加入输入检测和反馈，比如错误提示，修改之后的状态等。

**Comment by syscl** [comment]
@transtone 感谢你的提醒, 我会在近期修正这个问题. 毕竟太忙了, 现在才回复你.

---
@transtone Thks for you tips, I will refine it later. Still busy these day.

syscl

**Comment by syscl** [comment]
@transtone 
感谢你的反馈, 已经修改成更简单的形式了[参看这里] (https://github.com/syscl/Enable-HiDPI-OSX/commit/f017ae578e12af804011804388bc8547a641a48f). 感谢名单参看README.md

--

@transtone Thks for your suggestion, I have switched to a more precise message display [refer here] (https://github.com/syscl/Enable-HiDPI-OSX/commit/f017ae578e12af804011804388bc8547a641a48f). See credits in README.md

syscl
syscl
