### ISSUE TITLE
请问 我按照操作，重启电脑后列表中有1440x810，但点击就是不切换 是什么原因？

### ISSUE THREAD

**Issue by zestzone007** [syscl/Enable-HiDPI-OSX#57]
我按照上面的操作 重启电脑后，列表中有1440x810，但点击就是无法切换，我的笔记本电脑是装的黑苹果 最新的10.14，屏幕分辨率是 1920x1080

**Comment by zestzone007** [comment]
用其他博主的方式实现了

**Comment by T1nyeyes** [comment]
@zestzone007 您好，我遇到了类似的问题，也是点击(1920x1080 HiDPI)无法切换，请问您当时是怎么解决的呀？
