### ISSUE TITLE
AMD HD5770

### ISSUE THREAD

**Issue by kiddlu** [syscl/Enable-HiDPI-OSX#6]
EDID report:

```
        Time: 18:16:35
        Date: 2016年7月29日
        EDID Manager Version: 1.0.0.14
___________________________________________________________________

Block 0 (EDID Base Block), Bytes 0 - 127,  128  BYTES OF EDID CODE:

            0   1   2   3   4   5   6   7   8   9   
    000  |  00  FF  FF  FF  FF  FF  FF  00  10  AC
    010  |  9C  A0  4C  55  41  30  2A  17  01  03
    020  |  0E  35  1E  78  EA  A0  A5  A6  56  52
    030  |  9D  27  0F  50  54  A5  4B  00  71  4F
    040  |  81  80  A9  C0  D1  C0  01  01  01  01
    050  |  01  01  01  01  02  3A  80  18  71  38
    060  |  2D  40  58  2C  45  00  0F  29  21  00
    070  |  00  1E  00  00  00  FF  00  56  46  38
    080  |  58  32  33  41  4A  30  41  55  4C  0A
    090  |  00  00  00  FC  00  44  45  4C  4C  20
    100  |  50  32  34  31  34  48  0A  20  00  00
    110  |  00  FD  00  38  4C  1E  53  11  00  0A
    120  |  20  20  20  20  20  20  00  3F
```

(8-9)       ID Manufacture Name : DEL
(10-11)     ID Product Code     : A09C
(12-15)     ID Serial Number    : 0AUL
(16)        Week of Manufacture : 42
(17)        Year of Manufacture : 2013

(18)        EDID Version Number : 1
(19)        EDID Revision Number: 3

(20)        Video Input Definition: Analog
            0.700, 0.300 (1.000 V p-p)
            Separate Syncs, Composite Syncs, Syncs on Green

(21)        Maximum Horizontal Image Size: 53 cm
(22)        Maximum Vertical Image Size  : 30 cm
(23)        Display Gamma                : 2.20
(24)        Power Management and Supported Feature(s):
            Standby, Suspend, Active Off/Very Low Power, RGB Color, Non-sRGB, Preferred Timing Mode

(25-34)     Color Characteristics
            Red Chromaticity   :  Rx = 0.650  Ry = 0.338
            Green Chromaticity :  Gx = 0.320  Gy = 0.609
            Blue Chromaticity  :  Bx = 0.150  By = 0.057
            Default White Point:  Wx = 0.313  Wy = 0.329

(35)        Established Timings I

```
        720 x 400 @ 70Hz (IBM, VGA)
        640 x 480 @ 60Hz (IBM, VGA)
        640 x 480 @ 75Hz (VESA)
        800 x 600 @ 60Hz (VESA)
```

(36)        Established Timings II

```
        800 x 600 @ 75Hz (VESA)
        1024 x 768 @ 60Hz (VESA)
        1024 x 768 @ 75Hz (VESA)
        1280 x 1024 @ 75Hz (VESA)
```

(37)        Manufacturer's Timings (Not Used)

(38-53)     Standard Timings

```
        1152x864 @ 75 Hz (4:3 Aspect Ratio)
        1280x1024 @ 60 Hz (5:4 Aspect Ratio)
        1600x900 @ 60 Hz (16:9 Aspect Ratio)
        1920x1080 @ 60 Hz (16:9 Aspect Ratio)
```

(54-71)     Detailed Descriptor #1: Preferred Detailed Timing (1920x1080 @ 60Hz)

```
        Pixel Clock            : 148.5 MHz
        Horizontal Image Size  : 527 mm
        Vertical Image Size    : 297 mm
        Refresh Mode           : Non-interlaced
        Normal Display, No Stereo

        Horizontal:
            Active Time     : 1920 Pixels
            Blanking Time   : 280 Pixels
            Sync Offset     : 88 Pixels
            Sync Pulse Width: 44 Pixels
            Border          : 0 Pixels
            Frequency       : 67 kHz

        Vertical:
            Active Time     : 1080 Lines
            Blanking Time   : 45 Lines
            Sync Offset     : 4 Lines
            Sync Pulse Width: 5 Lines
            Border          : 0 Lines

        Digital Separate, Horizontal Polarity (+), Vertical Polarity (+)

        Modeline: "1920x1080" 148.500 1920 2008 2052 2200 1080 1084 1089 1125 +hsync +vsync
```

(72-89)     Detailed Descriptor #2: Monitor Serial Number

```
        Monitor Serial Number: VF8X23AJ0AUL
```

(90-107)    Detailed Descriptor #3: Monitor Name

```
        Monitor Name: DELL P2414H
```

(108-125)   Detailed Descriptor #4: Monitor Range Limits

```
        Horizontal Scan Range: 30kHz-83kHz
        Vertical Scan Range  : 56Hz-76Hz
        Supported Pixel Clock: 170 MHz
        Secondary GTF        : Not Supported
```

(126-127)   Extension Flag and Checksum

```
        Extension Block(s)  : 0
        Checksum Value      : 63
```

**Comment by kiddlu** [comment]
黑苹果，10.9.5，尝试了FixEDID的注入方法还有手动注入或者这个脚本，都不行。

我这边还有一张NV 740也不行。没有尝试过DSDT注入。BIOS是模拟iMAC的，回头模拟下MBP试试。

**Comment by syscl** [comment]
@kiddlu 十分感谢你如此详细的反馈, 我们两个的显示器好像是一样的, 都是Dell P2414H, 不过现在不在我身边, 我晚些的时候给你反馈. 不知道是不是这个显示器本身的问题, 或者是显卡的问题.

能麻烦你提供一下下面指令输出的信息给我吗?
```sh
ioreg -lw0 | grep -i "IODisplayEDID"
```

谢谢!
syscl

**Comment by kiddlu** [comment]
EDID最头上就有。

我昨天去tonymac还有国外一些黑苹果社区转了下，发现这个问题是有的人会出现有的人不会。

还有一个论坛说到NV的工程师在10.8.3往后升级，就把这个hack给堵死了。受到他的启发，我装了10.8.5用FIXEDID生成overrides，可以用。

但是10.9.x不少人也都能用，说明这个功能在windowserver这个层面应该是没有封的，所以我怀疑这个属于驱动问题。

我等下看看能不能把10.8.5的驱动放到10.9.5上试试，如果行不通，只能老是呆在10.8了，还是要谢谢你提供这么好用的脚本。

**Comment by syscl** [comment]
我知道, 我是需要看看终端中输出的形式上面有没有我没有考虑到的情况.

这个能提供一下链接吗, 这样我好反编译看看到底是哪里的问题导致的. 

我在几台机子上试过, 有时候可以用, 有时候不行, 但是一旦可以, 就没有问题, 所以我怀疑是OS X做了限制. 核显貌似成功率高一些.

syscl

**Comment by kiddlu** [comment]
➜  android-platform-knife git:(android-L) ioreg -lw0 | grep EDID
    | |   |   | |   |       "IODisplayEDID" = <00ffffffffffff0010ac9aa04c4a563401180104a5351e783aa0a5a656529d270f5054a54b00714f8180a9c0d1c00101010101010101023a801871382d40582c45000f292100001e000000ff00564638583234313334564a4c0a000000fc0044454c4c205032343134480a20000000fd00384c1e5311000a202020202020008b>
------------------------------------------------------------------------


http://www.insanelymac.com/forum/topic/290097-guide-108-add-your-custom-retina-hidpi-resolution-for-your-desktop-display/

第八楼

**Comment by kiddlu** [comment]
以及21楼：

Well, all I know is, they(nvidia and nvidia team in apple) added new mechanism in nvidia drivers onwards the 10.8.4 and later (including 10.9), to check the added or overridden resolutions. I had to revert to the older nvidia drivers from 10.8.3 while I'm being on 10.8.4 and 10.8.5 and it did work. But for 10.9 I'm out of luck. The old drivers aren't even linking on the 10.9… I already tried the nvidia web drivers too.

**Comment by kiddlu** [comment]
基本上确定就是驱动的问题了，AMD HD5770 10.8.5可以，10.9.0不行，驱动架构都变了。

NV GT740，10.8.3可以，10.8.5不行。估计INTEL的没怎么封，所以成功率高。

**Comment by syscl** [comment]
@kiddlu Nice, 十分感谢你这么重要的信息！！ Thks!!

--
@kiddlu Nice, thank your very much for such important information you provided for me!! Thks!!

syscl

**Comment by syscl** [comment]
我又更新了, 增加了

<key>dmdg</key>
请尝试.

syscl

**Comment by kiddlu** [comment]
感谢，试过了，仍然没效果。可能真的是驱动限制太死了。我现在是10.9.5 + AMD HD5770 + DELL P2416D，2K显示开到1280x720还是不错的。希望你早日取得成果！
