### ISSUE TITLE
Cannot Enable HiDPI.

### ISSUE THREAD

**Issue by PMheart** [syscl/Enable-HiDPI-OSX#7]
All right. And I bought a new monitor and I tried your script. The situation is just like I said @PCBeta. I've removed the previous EDID of my old monitor and boot with CsrActiveConfig=0x67 & BooterConfig=0x2a (Set via NVRAM natively, not using Clover to inject). Then I tried to add 1920x1080, 960x540 (half resolution), 3840x2160 (2x resolution), 1600x900 (Maybe I preferred this one...). Then reboot I cannot see the new solution in System Preferences or RDM app.
Need help. :)
PMheart

**Comment by syscl** [comment]
Please post at least EDID information by typing 
```sh
ioreg -lw0 | grep -i "IODisplayEDID"
```
Provide your original EDID folder/directory and ioreg as well.

Also see [issue#6] (https://github.com/syscl/Enable-HiDPI-OSX/issues/6#issuecomment-236407014) to have a sense of the patching failure, maybe you can try 10.8.x (x <= 3)for further confirmation.

syscl

**Comment by PMheart** [comment]
No longer having my original EDID... Reinstalling OS X.

**Comment by PMheart** [comment]
Now I have reinstalled 10.11.6. Here’s my EDID:
00ffffffffffff0005e38021ae0e0000191a0103682e1a782aeed1a555489b26125054bfef00d1c0b30095008180814081c001010101023a801871382d40582c4500ca021100001e000000fd00324c1e5311000a202020202020000000fc0032313830570a20202020202020000000ff00414e38303632355a303337353800c

**Comment by PMheart** [comment]
Oops. Still cannot after execute ur script...
Here is the new EDID.
00ffffffffffff0005e38021ae0e0000191a0103682e1a782aeed1a555489b26125054bfef00d1c0b30095008180814081c001010101023a801871382d40582c4500ca021100001e000000fd00324c1e5311000a202020202020000000fc0032313830570a20202020202020000000ff00414e38303632355a303337353800c1
Seems doesnt change anything.
Here is the EDID folder.
[DisplayVendorID-05e3.zip](https://github.com/syscl/Enable-HiDPI-OSX/files/392331/DisplayVendorID-05e3.zip)

**Comment by syscl** [comment]
@PMheart How about the original/untouch EDID directory/folder. This one you upload for me is the one that generated by the Enable-HiDPI-OSX, I need to compare both of the files and see what's going on. But as I said in other thread, I am still busy doing non-hack related job these days.

syscl

**Comment by PMheart** [comment]
Yes. OS X does not have DisplayVendorID-05e3 folder by default. And this is generated by your script I believe.

**Comment by syscl** [comment]
I have since updated with following strings/lines
```sh
<key>dmdg</key>                                                                                                     
 <data>AAAAAg==</data>
```
Try the latest one. FYI, just built in display or fake vid of display as 0A5C(Apple.Inc) is not enough to enable HiDPI.

syscl

**Comment by PMheart** [comment]
Now I've enabled HiDPI. Thanks anyway.

**Comment by PMheart** [comment]
But I think just need this data is not enough, maybe you need DisplayNub.kext to FYI?

**Comment by PMheart** [comment]
All right. Tested. Actually it's not necessary to inject EDID to enable HiDPI, and sometimes it will affect HiDPI output. The only thing that helped we enable HiDPI is just add resolution in the corresponding DisplayVendorID-xxxx/DisplayProductID-xxxx (Actually a plist). Nothing more. And now I am using DisplayNub.kext to inject the resolution that I need and fake VID as Apple, PID as iMac Built-In Display. All works fine. I don't touch /System/Library/Displays/Contents/Resources/Overrides since it will be broken after software update and SIP will deny this operation.
